#!/bin/bash

runLine="\n--------------------- RUN ---------------------\n\n" 
doneLine="\n--------------------- DONE --------------------\n\n" 

while true; do
    find -regextype posix-extended -regex "\./(src|test|app).*|.*\.cabal" |
        entr -d sh -c "stack build && printf \"$runLine\" && stack \"$1\" \"$2\" && printf \"$doneLine\""
done
